Add simple test to verify that incrementakl fast import works.

diff --git a/test/fi-to-fi b/test/fi-to-fi
--- a/test/fi-to-fi
+++ b/test/fi-to-fi
@@ -21,6 +21,8 @@
 # To add complexity to a test load, do -n, then edit the test repo with
 # git, then use -o.
 #
+# With -v, dump the location of the test repo (use with -n)
+#
 # The REPOSURGEON environment variable can be used to substitute in a
 # different implementation.
 #
@@ -33,15 +35,17 @@ extract=True
 view=False0
 stream=True
 cleanup=True
+verbose=False
 
 tmpdir=${TMPDIR:-/tmp}
 
-while getopts gno opt
+while getopts gnov opt
 do
     case $opt in
 	g) extract=True ;  view=True; stream=False ; cleanup=False ;;
 	n) extract=True ;  view=False; stream=False ; cleanup=False ;;
         o) extract=False ; view=False; stream=True  ; cleanup=False ;;
+	v) verbose=True ;;
 	*) echo "$0: unknown flag $opt" >&2; exit 1;;
     esac
 done
@@ -55,7 +59,11 @@ testrepo=${1:-${tmpdir}/test-repo$$}
 if [ $extract = True ]
 then
     rm -fr "$testrepo"; mkdir "$testrepo"
-    (cd "$testrepo" >/dev/null || (echo "$0: cd failed" >&2; exit 1); git init --quiet; git fast-import --quiet; git checkout) 
+    (cd "$testrepo" >/dev/null || (echo "$0: cd failed" >&2; exit 1); git init --quiet; git fast-import --quiet; git checkout)
+    if  [ ${verbose} = True ]
+    then
+	echo "${testrepo}"
+    fi
 fi
 
 # Should we view the repo?
