Implement TODO/SKIP handling in liftcheck and singletest.

diff --git a/test/liftcheck b/test/liftcheck
--- a/test/liftcheck
+++ b/test/liftcheck
@@ -32,6 +32,9 @@ If the comparison produces a nonempty diff, it is output as a YAML
 block following the "not ok" line.  If the environment variable
 QUIET is set to 1, the diff is suppressed.
 
+If the ## line of the stream file contains the string TODO, any
+TAP line generated by test failure or success will have a TODO directive.
+
 The -v option reveals executed subcommands.
 The -q option makes repotool extra quiet and reports only errors.
 The -p option shows revision numbers when comparing multiple revisions
@@ -105,13 +108,21 @@ do
     export TMPDIR
     mkdir "${TMPDIR}"
 
-    # shellcheck disable=SC2039
     description=$(sed -n <"${what}" -e '/ ##  */s///p' || echo 'no description')
+    directive=""
+    if grep ' ##.*TODO' "${what}" >/dev/null
+    then
+	directive='# TODO '
+    elif grep ' ##.*SKIP' "${what}" >/dev/null
+    then
+	echo "ok - $ SKIP ${what}: ${description}"
+	exit 0
+    fi
 
     # Make a Subversion repo from the dump
     # shellcheck disable=SC2086
     ./svn-to-svn ${svnquiet} ${slimit} -c <${what} ${stem} \
-    	|| { echo "not ok - ${what}: svn-to-svn within liftcheck failed"; exit 1; }
+    	|| { echo "not ok - ${directive}${what}: svn-to-svn within liftcheck failed"; exit 1; }
 
 
     cat /dev/null >/tmp/warnings$$
@@ -224,7 +235,7 @@ do
 	    ../${REPOTOOL:-repotool} compare ${repotoolopt} ${compareopt} \
 		-a ${refopt} -r ${intrev}:${sha} \
 		${stem}-checkout ${stem}-git >>/tmp/diff$$ 2>>/tmp/warnings$$ \
-		|| { echo "not ok - ${what}: repotool within liftcheck failed"; exit 1; }
+		|| { echo "not ok - ${directive}${what}: repotool within liftcheck failed"; exit 1; }
 	done < "${stem}.info"
     else
 
@@ -240,27 +251,27 @@ do
 	# shellcheck disable=SC2086
 	../${REPOTOOL:-repotool} compare-all ${repotoolopt} ${compareopt} \
 	   ${stem}-checkout ${stem}-git  tee /tmp/diff$$ 2>>/tmp/warnings$$ \
-	    || { echo "not ok - ${what}: repotool within liftcheck failed"; exit 1; }
+	    || { echo "not ok - ${directive}${what}: repotool within liftcheck failed"; exit 1; }
     fi
 
     if [ ! -s /tmp/diff$$ ]
     then
-	echo "ok - ${what}: ${description}"
+	echo "ok - ${directive}${what}: ${description}"
 	if [ ! "${QUIET}" = 1 ]
 	then
 	    sed </tmp/warnings$$ -e 's/^/ /'
 	fi
 	exit 0
     else
-	echo "not ok - ${what}: ${description}"
-	if [ ! "${QUIET}" = 1 ]
+	echo "not ok - ${directive}${what}: ${description}"
+	if [ "${directive}" = "" ] && [ ! "${QUIET}" = 1 ]
 	then
 	    echo "  --- |"
 	    sed </tmp/warnings$$ -e 's/^/  /'
 	    sed </tmp/diff$$ -e 's/^/  /'
 	    echo "  ..." 
 	fi
-	exit 1
+	[ "${directive}" = "" ] && exit 1 
     fi
     
     if [ $debug != no ]
